### ISSUE TITLE
command ‘scriptable.initialize’ not found

### ISSUE THREAD

**Issue by fade-color** [gebeto/scriptable-vscode#1]
Command ‘Scriptable: Initialize sources’ resulted in an error (command ‘scriptable.initialize’ not found)

**Comment by gebeto** [comment]
I will check it today a bit later

**Comment by gebeto** [comment]
Currently I've found the issue, but didn't have enough time to investigate and fix it

It is working in developer mode, but it is not working after publishing

**Comment by gebeto** [comment]
Wow, fixed!
